ratio: (.7, 0.15,0.15)

AUGMENTATION:
  horizontal_flip: True
  vertical_flip: True
  rotation_range: 90
  zoom_range: 0.2
  shear_range: 0.2
  width_shift_range: 0.2
  height_shift_range: 0.2
  target_size: [224,224]

Model_Building:
  units: 2
  activation: softmax
  epochs: 1 
  input_shape: [224,224,3]

Model_Checkpoint:
  monitor: accuracy
  save_best_only: True
  save_weights_only: False
  verbose: 1

Early_stopping:
  patience: 2
  restore_best_weights: True

ReduceLROnPlateau:
  factor: 0.2
  min_lr: 0.0001

EPhocs:
  ephocs: 1
