ratio: (.7, 0.15,0.15)

AUGMENTATION:
  horizontal_flip: True
  vertical_flip: True
  rotation_range: 90
  zoom_range: 0.2
  shear_range: 0.2
  width_shift_range: 0.2
  height_shift_range: 0.2
  target_size: (224,224,3)

Model_Building:
  units: 2
  activation: softmax
  epochs: 1 
  input_shape: [224,224,3]
