data_root: data

data_ingestion:
  root_dir: data/data_ingestion
  source_URL: https://drive.google.com/file/d/1BoMmXX1A0bc-inv1QK19Ci6L-r96iXjv/view?usp=drive_link
  local_data_file: data/data_ingestion/Chicken_fecal.zip
  unzip_dir: data/data_ingestion/extracted_files/


data_splitting:
  root_dir: data/data_splitting
  raw_data_dir: data/data_ingestion/extracted_files/Chicken-fecal-images/
  output_data: data/data_splitting
  

data_aug:
  root_dir: data/data_augmented
  train_data: data/data_splitting/train
  test_data: data/data_splitting/test
  val_data: data/data_splitting/val
  train_data_aug: data/data_augmented/train
  test_data_aug: data/data_augmented/test
  val_data_aug: data/data_augmented/val

Model_Building:
  root_dir: data/model_building
  model_save: data/model_building/Chicken_fecal.keras

Model_Checkpoint:
  root_dir: data/model_checkpoint
  model_save: data/model_checkpoint/Chicken_fecal_with_callbacks.keras
  existing_model: data/model_building/Chicken_fecal.keras
